require("dotenv").config();
const express = require("express");
const path = require("path");
const { Telegraf } = require("telegraf");
const app = express();
const server = require("http").createServer(app);
const webSocketServer =  require("./socketServer");
const build = path.join(__dirname, "svelte/public");
const tele = new Telegraf(process.env.TGID);
clients = [];
curUser = null;
let con = null;
app.use(express.static(build));
app.use('/notes',require('./routes/notes'));
app.use('/info',require('./routes/info'));
webSocketServer.initWeSocketServer(server);
server.listen(process.env.PORT, () => {
  console.log(`realnotes listening on port ${process.env.PORT}`);
});
tele.startPolling();